### ISSUE TITLE
[BUG] On blur validation triggers change event

### ISSUE THREAD

**Issue by romain-rhieu** [formio/formio.js#1627]
Hello FormioJs Team,

We have set the ValidateOn property of a component to trigger validation on " blur" .

Nevertheless, validation is triggered on the change event (whenever I enter a character), is it normal ?

To test : https://jsfiddle.net/ak78qc0L/

It seems to be similar as https://github.com/formio/angular-formio/issues/238

Regards,

Romain

**Comment by jhen1422** [comment]
@romain-rhieu 
We appreciate the report. This item has been replicated and added to our platform backlog. If you are needing this fix expedited, please contact support@form.io for pricing information.

Thanks again!

**Comment by phucduong86** [comment]
Hi, we are experiencing the same issue.
Can I please be added to your back log ticket so I'm notified when it is resolved?
Thank you

**Comment by wag110894** [comment]
@phucduong86 @romain-rhieu,

This is has been resolved. You can use the latest version 4.9.20.

**Comment by phucduong86** [comment]
@wag110894 
I've used version 4.9.20, 4.9.22 and 4.9.25 and the issue still persists.

I've also tested using the Form Viewer Pro out of the box with On Premise portal - which uses Renderer version 4.9.22 and the issue is still there.

**Comment by phucduong86** [comment]
Here's my codepen example with 4.9.20
https://codepen.io/duongph/pen/wvBBzVe?editors=1010

**Comment by wag110894** [comment]
@phucduong86 Thank you for providing additional content for this issue. I have reopened the ticket for this issue on our side. We will let you know once this issue is resolved. For reference, the ticket number is FJS-359.

**Comment by jhen1422** [comment]
@phucduong86 
This issue has been resolved in the 4.10x branch of formio.js. Please note this branch has not yet gone through a full regression test cycle

**Comment by fabien-feat** [comment]
Hello ! I need to reopen this issue...
In fact, it works fine ! But when you add a button (perhaps, other component) it fail.
Here is a JsFiddle with 4.9.26 version, but you can test with any version it the same.

https://jsfiddle.net/fabienfeat/58hq1L9p/

**Comment by wag110894** [comment]
@fabien-feat as mentioned above, this fix is located in the 4.10.17 branch, so you will not see the fix inside 4.9.266.

**Comment by fabien-feat** [comment]
@wag110894 yes I've seen @jhen1422 comment... but...
First, there is no 4.10.17 branch, perhaps you meant 4.10.0-beta.17 (where I have seen related commits) ?
Second if you test my JsFiddle in 4.10.0-rc.6, bug is allready there...

**Comment by phucduong86** [comment]
@wag110894 
I've updated the lib to latest version 4.10.0-rc.6
For one single component it works as expected, however there might have been a regression issue.

https://codepen.io/duongph/pen/wvBBzVe?editors=1010

## Reproduce:
1. Type a few digits in Field 1 (eg: 1234)
2. Tab to Field 2
3. Start typing in Field 2 (eg: 1234)
4. Tab out of Field 2

## Expected:
Step 3: When you start typing in Field 2, the Error message for Field 1 should stay the same
Step 4: Field 2 should get validated and shows an error
## Actual:
Step 3: The error message in field 1 gets removed
Step 4: Both Field 1 and Field 2 gets validated and errors updated

**Comment by wag110894** [comment]
@phuc

**Comment by cmarcal** [comment]
Hi !!
I need to fix is done in any old or new branch, because need to solutions for my job =(

**Comment by jhen1422** [comment]
@phucduong86 This issue is resolved in version 4.10.0-rc.9

**Comment by fabien-feat** [comment]
@jhen1422 Hi ! I'm sorry but... issue is still there...
https://jsfiddle.net/fabienfeat/58hq1L9p/11/

**Comment by fabien-feat** [comment]
:up: ?

**Comment by cmcortez** [comment]
We are not able to replicate the issue. As part of a support package, we can schedule a call with a developer to investigate further investigate the issue. If you are interested please write directly to support@form.io and reference the GitHub issue link.
