### ISSUE TITLE
Submission render only renders wizard format

### ISSUE THREAD

**Issue by gregbown** [formio/formio.js#1752]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [X] Local deployment
    - Version: 
- Formio.js version: 4.0.8
- Frontend framework: NodeJS
- Browser: Chrome
- Browser version:

## Steps to Reproduce
1. duplicate structure as in [demo ](https://formio.github.io/formio.js/app/examples/htmlview.html)
2. create form and submission using form layout.
3. create form and submission using wizard layout
4. only the wizard layout will render as HTML.

## Expected behavior
View both types of form layouts should render as html
## Observed behavior
wizard layout form renders as HTML, form layout will not render as HTML. The input fields are blank. Note: the form layout will render as read only/form
## Example
If possible, please provide a screenshot

**form**
![form](https://user-images.githubusercontent.com/1952728/65567550-8b869c80-df0b-11e9-9d1f-a2cde416e6a6.jpg)

**wizard**
![wizard](https://user-images.githubusercontent.com/1952728/65567554-90e3e700-df0b-11e9-8818-6a91a4c7207d.jpg)

**Comment by jhen1422** [comment]
@gregbown 
Can you try using the latest version for formio.js to see if that resolves your issue?

**Comment by gregbown** [comment]
@jhen1422 I have tried version 4.2.0 and it behaves the same, the values of the submission are not rendered.

I have tried stepping through the execution of both to see the difference but it is extremely difficult to spot with the compiled code, wishing I could run it on the src code to see where it breaks. :(

**Comment by wag110894** [comment]
@gregbown Can you try using the latest version of formio.js to see if this resolves your issue?

The latest version is 4.7.7.

Thanks,

**Comment by gregbown** [comment]
@wag110894  I am using 4.8.0-beta.1 and neither form or wizard will render as html, however; I am calling the setter [here]([url](https://github.com/formio/formio.js/blob/master/src/Webform.js#LC695)) to set the submission now. The other render mode "form" works fine but "html" fails on both now.

```
Formio.createForm(
  document.getElementById('modalFormio'),
  window.BUILDER.formio.instance.builder.form,
  {readOnly: true, renderMode: 'html'}
).then(window.BUILDER.formio.instance.onModalForm)

/* Once the modal form create method promise resolves */
BUILDER.formio.prototype.onModalForm = function(form) {
  if (typeof form === 'undefined')
    throw 'Modal form is undefined in onModalForm event';
  // Use setter see: formiojs/src/Webform.js line 696
  form.submission = {data: window.BUILDER.formio.instance.form.submission.data};
};
```

**Comment by randallknutson** [comment]
We did have some minor changes with renderMode but nothing that should cause issues. It is possible that a component is causing issues with it now though. We have tested this as part of testing and it worked correctly for us. Can you try to isolate if there is a specific component that is causing issues with the latest? If you could provide an example it would help us fix it.

**Comment by gregbown** [comment]
@randallknutson In version 4.8.0-beta.2 the Wizard is working properly again with options:
```
{readOnly: true, renderMode: 'html'}
```
Form remains as pictured above and does not render the values. Tested text input, password, email and phone number values.

Than you for the progress though, since I am using the wizard exclusively now.

**Comment by randallknutson** [comment]
No problem. Glad it is resolved.

**Comment by yuzdeng** [comment]
Is there any update for this bug @randallknutson ? I met the same issue as @gregbown . When I set the options:
```
{readOnly: true, renderMode: 'html'}
```
Text input didn't show the value.

**Comment by randallknutson** [comment]
Upgrading to a newer version should fix it.

**Comment by hisuwh** [comment]
I'm still getting this issue with vue-formio@4.0.7 and formiojs@4.11.3

form:
```json
{
   "components":[
      {
         "label":"Text Field",
         "labelPosition":"top",
         "placeholder":"",
         "description":"",
         "tooltip":"",
         "prefix":"",
         "suffix":"",
         "widget":{
            "type":"input"
         },
         "inputMask":"",
         "allowMultipleMasks":false,
         "customClass":"",
         "tabindex":"",
         "hidden":false,
         "hideLabel":false,
         "showWordCount":false,
         "showCharCount":false,
         "mask":false,
         "autofocus":false,
         "spellcheck":true,
         "disabled":false,
         "tableView":true,
         "modalEdit":false,
         "multiple":false,
         "persistent":true,
         "inputFormat":"plain",
         "protected":false,
         "dbIndex":false,
         "case":"",
         "encrypted":false,
         "redrawOn":"",
         "clearOnHide":true,
         "customDefaultValue":"",
         "calculateValue":"",
         "calculateServer":false,
         "allowCalculateOverride":false,
         "validateOn":"change",
         "validate":{
            "required":false,
            "pattern":"",
            "customMessage":"",
            "custom":"",
            "customPrivate":false,
            "json":"",
            "minLength":"",
            "maxLength":"",
            "strictDateValidation":false,
            "multiple":false,
            "unique":false
         },
         "unique":false,
         "errorLabel":"",
         "key":"textField",
         "tags":[
            
         ],
         "properties":{
            
         },
         "conditional":{
            "show":null,
            "when":null,
            "eq":"",
            "json":""
         },
         "customConditional":"",
         "type":"textfield",
         "input":true,
         "refreshOn":"",
         "attributes":{
            
         },
         "overlay":{
            "style":"",
            "left":"",
            "top":"",
            "width":"",
            "height":""
         },
         "inputType":"text",
         "id":"ezl5gjl",
         "defaultValue":null
      },
      {
         "type":"button",
         "label":"Submit",
         "key":"submit",
         "size":"md",
         "block":false,
         "action":"submit",
         "disableOnInvalid":true,
         "theme":"primary",
         "input":true,
         "placeholder":"",
         "prefix":"",
         "customClass":"",
         "suffix":"",
         "multiple":false,
         "defaultValue":null,
         "protected":false,
         "unique":false,
         "persistent":false,
         "hidden":false,
         "clearOnHide":true,
         "refreshOn":"",
         "redrawOn":"",
         "tableView":false,
         "modalEdit":false,
         "labelPosition":"top",
         "description":"",
         "errorLabel":"",
         "tooltip":"",
         "hideLabel":false,
         "tabindex":"",
         "disabled":false,
         "autofocus":false,
         "dbIndex":false,
         "customDefaultValue":"",
         "calculateValue":"",
         "calculateServer":false,
         "widget":{
            "type":"input"
         },
         "attributes":{
            
         },
         "validateOn":"change",
         "validate":{
            "required":false,
            "custom":"",
            "customPrivate":false,
            "strictDateValidation":false,
            "multiple":false,
            "unique":false
         },
         "conditional":{
            "show":null,
            "when":null,
            "eq":""
         },
         "overlay":{
            "style":"",
            "left":"",
            "top":"",
            "width":"",
            "height":""
         },
         "allowCalculateOverride":false,
         "encrypted":false,
         "showCharCount":false,
         "showWordCount":false,
         "properties":{
            
         },
         "allowMultipleMasks":false,
         "leftIcon":"",
         "rightIcon":"",
         "dataGridLabel":true,
         "id":"etfu44b"
      }
   ]
}
```

submission:
```json
{
   "data":{
      "textField":"slkfjsdkls",
      "submit":false
   }
}
````
options:
```json
{
    "readOnly": true,
    "renderMode": "html"
}
```

**Comment by wag110894** [comment]
Hello @hisuwh, 
We are aware of this issue and it is currently being worked on by one of our developers. For reference, the ticket number is FJS-1070. We will let you know once this issue is resolved.

Thank you.
