### ISSUE TITLE
[BUG] save/load roundtrip broken for "This component should display: False" in Conditional tab

### ISSUE THREAD

**Issue by franke-mc** [formio/formio.js#1961]
## Environment
- Hosting type
  - [x] Form.io
- Formio.js version: 4.5.0, react-formio
- Browser: firefox 70.0

## Example on next.form.io:
- see [this form](https://api.form.io/project/5d1c9ef99cf71913daa0e494/form/5db498531d29d2a19258ed5d)

## Steps to Reproduce
1. Create a form with a component
2. Go to the "Conditional" tab
3. Enter a simple rule starting with "This component should display: 'False'" , e.g. "when component 'Submit' has the value 'true'.
4. Save the component and the form
5. Edit the form again, edit the component, got to the Conditional tab

## Expected behavior
`False` is displayed as selected as originally entered.

## Observed behavior
The first selection is empty.
![conditionalFalseNotDisplayed](https://user-images.githubusercontent.com/46748541/67624979-59cd6200-f838-11e9-9c04-8095695c6af6.png)

Note that the relevant part in the form json is:
`"conditional":{"show":false,"when":"submit","eq":"true","json":""}`

**Comment by jhen1422** [comment]
@franke-mc 
Thank you for the report. We were able to replicate this issue on our end as well and have created a ticket in our 4x branch. We will review during our planning meeting next week. Please note, we welcome pull requests in this library. If you need this item expedited, please feel free to contact support@form.io for pricing.

**Comment by sutauma** [comment]
This behavior is reproducable on all false values over the whole platform (Component conditionals or data). For example, if you create a radio button (true/false, boolean) the data field after submit is empty. If you click on view the form displays true even though the data entry is false/empty.

**Comment by wag110894** [comment]
Hello,

Thank you for your patience while we worked on getting this issue resolved. 

This issue has been resolved in the latest version of our formio.js 4.8.0-rc3

Thank you.

**Comment by franke-mc** [comment]
@wag110894: Thanks, it's fine now. (It still shows "false" while the original options are "False" & "True" with capital letters, but that's a rather cosmetic issue. In fact, I would have expected the original options to be "false" & "true" with lower-case letters, too...)
