### ISSUE TITLE
Unhandled promise rejection for invalid submission

### ISSUE THREAD

**Issue by josefernand** [formio/formio.js#249]
There is an uncaught promise rejection thrown in the form validation when the submission is invalid and unfortunately this is breaking our automated tests.
The rejection is in the `executeSubmit()` in the `FormioForm` class. Digging in a bit deeper I found the only place that this rejection is catched is in a test. Is there any other reason to throw this rejection? Thanks and If I can help in some way just let me know. 

```javascript
executeSubmit() {
    let submission = this.submission;
    if (
      submission &&
      submission.data &&
      this.checkValidity(submission.data, true)
    ) {
      this.loading = true;
      if (this.nosubmit || !this.formio) {
        return this.onSubmit(submission, false);
      }
      return this.formio.saveSubmission(submission)
        .then(
          (result) => this.onSubmit(result, true)
        )
        .catch(
          (err) => this.onSubmissionError(err)
        );
    }
    else {
      this.showErrors();
      return Promise.reject('Invalid Submission');
    }
  }
```

**Comment by travist** [comment]
This is already fixed in master branch. I will roll a new version today.

**Comment by travist** [comment]
Should be fixed with version ```v2.22.1```

**Comment by josefernand** [comment]
Hi @travist thanks for the reply. The problem is still there, you can also check in the browser, the console will show an unhandled promise error when submitting an invalid form. 
I think the problem could be in the `'submitButton'` event handler that is not catching the `submit()` promise rejection (line 656 of `formio.form.js`).
I checked adding a catch there and it works passing the tests, but I don't know if there is another better way to handle it. Thanks.
