### ISSUE TITLE
[BUG] Dynamic Select Filtering - Refresh On does not work

### ISSUE THREAD

**Issue by kzhang-dsg** [formio/formio.js#3108]
## Environment
- Hosting type
  - [] Form.io
  - [x] Local deployment
    - Version: 
- Formio.js version: 4.10.x and above 
- Frontend framework: none
- Browser: Chrome
- Browser version: 84.0.4147.105

## Steps to Reproduce
1. Follow the documentation to setup Dynamic Select Filtering: https://help.form.io/tutorials/walkthroughs/dynamic-select-filtering/
2. Set the "Refresh On" to "Make" for the Model field.
3. Test the Dynamic Select Filtering

## Expected behavior
The Model options should refresh when the make field is changed.

## Observed behavior
The Model options do not refresh when the make field is changed for formio.js version: 4.10.x and above.

## Additional Notes:
1. When downgrading the formio.js version to 4.9.26, the refresh on function starts working,
2. For formio.js version: 4.10.x and above, if you set  "Refresh On" to "All", it will also work. But this is not really a workaround, because then the "Clear value on refresh" will clear the selection on any field changes.

**Comment by wag110894** [comment]
@kzhang-dsg have you seen this example: https://formio.github.io/formio.js/app/examples/external.html?

**Comment by kzhang-dsg** [comment]
@wag110894

Yes I have. 

Forgot to mention. the bug exists only with HTML5 widget. The Choose.js widget appears to work fine.

We need to use HTML5 widget for native mobile selection UI. The Choose.JS does not work very well out of the box on Mobile.

**Comment by wag110894** [comment]
Could you provide what Mobile Device you are using so we can test against the same device? can you also provide a video of the issue taking place?

**Comment by kzhang-dsg** [comment]
For local development, we just use Chrome. Mobile is just for future support. 

It is easy to reproduce. I just copied the example: https://formio.github.io/formio.js/app/examples/external.html and changed the widget to HTML5, you will see the issue: https://jsfiddle.net/uove48mc/

BTW,  the Choose.js widget also does not fully work. In summary:

1. For Choose.js, The model options refresh on change of the Make field. But it does NOT clear the value on change of the Make field.
3.For HTML5, The model options does NOT refresh on change of the Make field. It also does NOT clear the value on change of the Make field.

**Comment by wag110894** [comment]
@kzhang-dsg Thank you for your patience. We have created a ticket and have added this issue to our backlog. We welcome a PR or have a process to expedite if you are interested.  For reference, the ticket number is FJS-1141. 

We will let you know once this issue has been resolved.

Please let us know if you are interested in expediting this issue for you.

Have a great day!

**Comment by jhen1422** [comment]
@kzhang-dsg 
Issue should be resolved in formio.js version 4.12.0-rc19

**Comment by kzhang-dsg** [comment]
Just tested with version 4.12.0-rc19. Looks like the issue still exists: https://jsfiddle.net/952hnr1y/1/

**Comment by kzhang-dsg** [comment]
Hi @jhen1422 please reopen this issue as the issue is not fixed yet.

**Comment by kzhang-dsg** [comment]
I think the issue is with the `editgrid`.

If the select box is in a editgrid, then the changePath will become something like `"cars[0].make"`, which does not match the value in `refreshData` (which is just `"make"`): 

![image](https://user-images.githubusercontent.com/15915824/94567171-c7e08d00-0230-11eb-983e-7a3a11606be7.png)

**Comment by kzhang-dsg** [comment]
Created a pull request https://github.com/formio/formio.js/pull/3307

**Comment by VikkiAlenn** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. Please re-open if it is still relevant. Thank you for your contribution!
